apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: dremio
  name: dremio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dremio
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: dremio
    spec:
      containers:
        - env:
            - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
              value: -Dpaths.dist=file:///opt/dremio/data/dist
          image: dremio/dremio-oss:latest
          name: dremio
          ports:
            - containerPort: 9047
              protocol: TCP
            - containerPort: 31010
              protocol: TCP
            - containerPort: 32010
              protocol: TCP
      restartPolicy: Always
