apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nessie
  name: nessie
spec:
  ports:
    - name: "19120"
      port: 19120
      targetPort: 19120
  selector:
    io.kompose.service: nessie
