apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nessie
  name: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nessie
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nessie
    spec:
      containers:
        - image: projectnessie/nessie:latest
          name: nessie
          ports:
            - containerPort: 19120
              protocol: TCP
      restartPolicy: Always
