apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: superset
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: superset
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: superset
    spec:
      containers:
        - image: alexmerced/dremio-superset
          name: superset
          ports:
            - containerPort: 8088
              protocol: TCP
      restartPolicy: Always
